name: 'Production - Terraform Destroy'

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  production-terraform-destroy:
    uses: ./.github/workflows/terraform-destroy.yml
    with:
      environment: 'production'
      terraform_version: '1.9.7'
      region: 'eu-west-1'
    secrets:
      ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}
